version: '3.1'

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: potygen
      POSTGRES_USER: potygen
      POSTGRES_PASSWORD: dev-pass
    volumes:
      - ./initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
