import { UnaryOperatorTag, BinaryOperatorTag } from '@ovotech/potygen-ast';
import {
  TypeJson,
  TypeNull,
  TypeUnknown,
  TypeString,
  TypeBoolean,
  TypeNumber,
  TypeDate,
  TypeArrayConstant,
  TypeConstant,
  TypeAny,
  TypeBuffer,
  TypeObjectLiteralConstant,
} from './query-interface.types';

export const typeJson: TypeJson = { type: 'Json' };
export const typeNull: TypeNull = { type: 'Null' };
export const typeUnknown: TypeUnknown = { type: 'Unknown' };
export const typeAny: TypeAny = { type: 'Any' };
export const typeString: TypeString = { type: 'String' };
export const typeBuffer: TypeBuffer = { type: 'Buffer' };
export const typeBoolean: TypeBoolean = { type: 'Boolean' };
export const typeNumber: TypeNumber = { type: 'Number' };
export const typeDate: TypeDate = { type: 'Date' };

const arr = (items: TypeConstant): TypeArrayConstant => ({ type: 'ArrayConstant', items });

export const pgTypeAliases: Record<string, keyof typeof pgTypes> = {
  bigint: 'int8',
  bigserial: 'serial8',
  'bit varying': 'varbit',
  boolean: 'bool',
  character: 'char',
  'character varying': 'varchar',
  'double precision': 'float8',
  integer: 'int4',
  int: 'int4',
  numeric: 'decimal',
  real: 'float4',
  float: 'float4',
  smallint: 'int2',
  smallserial: 'serial2',
  serial: 'serial4',
  'time with time zone': 'timetz',
  'time without time zone': 'time',
  'timestamp without time zone': 'timestamp',
  'timestamp with time zone': 'timestamptz',
  array: 'anyarray',
};

export const pgTypes = {
  aclitem: typeString,
  cid: typeString,
  macaddr: typeString,
  macaddr8: typeString,
  smgr: typeString,
  tid: typeString,
  uuid: typeString,
  xid: typeString,
  interval: {
    type: 'ObjectLiteralConstant',
    items: [
      { name: 'years', type: typeNumber },
      { name: 'months', type: typeNumber },
      { name: 'days', type: typeNumber },
      { name: 'hours', type: typeNumber },
      { name: 'minutes', type: typeNumber },
      { name: 'seconds', type: typeNumber },
      { name: 'milliseconds', type: typeNumber },
    ],
  } as TypeObjectLiteralConstant,
  bytea: typeBuffer,
  reltime: typeString,
  tinterval: typeString,
  char: typeString,
  cstring: typeString,
  daterange: typeString,
  decimal: typeString,
  name: typeString,
  any: typeAny,
  anyelement: arr(typeString),
  anyenum: arr(typeString),
  anynonarray: typeAny,
  anyarray: arr(typeAny),
  anyrange: arr(typeString),
  event_trigger: typeString,
  fdw_handler: typeString,
  index_am_handler: typeString,
  internal: typeString,
  language_handler: typeString,
  opaque: typeString,
  pg_aggregate: typeString,
  pg_am: typeString,
  pg_amop: typeString,
  pg_amproc: typeString,
  pg_attrdef: typeString,
  pg_attribute: typeString,
  pg_auth_members: typeString,
  pg_authid: typeString,
  pg_available_extension_versions: typeString,
  pg_available_extensions: typeString,
  pg_cast: typeString,
  pg_class: typeString,
  pg_collation: typeString,
  pg_config: typeString,
  pg_constraint: typeString,
  pg_conversion: typeString,
  pg_cursors: typeString,
  pg_database: typeString,
  pg_db_role_setting: typeString,
  pg_ddl_command: typeString,
  pg_default_acl: typeString,
  pg_depend: typeString,
  pg_dependencies: typeString,
  pg_description: typeString,
  pg_enum: typeString,
  pg_event_trigger: typeString,
  pg_extension: typeString,
  pg_file_settings: typeString,
  pg_foreign_data_wrapper: typeString,
  pg_foreign_server: typeString,
  pg_foreign_table: typeString,
  pg_group: typeString,
  pg_hba_file_rules: typeString,
  pg_index: typeString,
  pg_indexes: typeString,
  pg_inherits: typeString,
  pg_init_privs: typeString,
  pg_language: typeString,
  pg_largeobject: typeString,
  pg_largeobject_metadata: typeString,
  pg_locks: typeString,
  pg_lsn: typeString,
  pg_matviews: typeString,
  pg_namespace: typeString,
  pg_ndistinct: typeString,
  pg_node_tree: typeString,
  pg_opclass: typeString,
  pg_operator: typeString,
  pg_opfamily: typeString,
  pg_partitioned_table: typeString,
  pg_pltemplate: typeString,
  pg_policies: typeString,
  pg_policy: typeString,
  pg_prepared_statements: typeString,
  pg_prepared_xacts: typeString,
  pg_proc: typeString,
  pg_publication: typeString,
  pg_publication_rel: typeString,
  pg_publication_tables: typeString,
  pg_range: typeString,
  pg_replication_origin: typeString,
  pg_replication_origin_status: typeString,
  pg_replication_slots: typeString,
  pg_rewrite: typeString,
  pg_roles: typeString,
  pg_rules: typeString,
  pg_seclabel: typeString,
  pg_seclabels: typeString,
  pg_sequence: typeString,
  pg_sequences: typeString,
  pg_settings: typeString,
  pg_shadow: typeString,
  pg_shdepend: typeString,
  pg_shdescription: typeString,
  pg_shseclabel: typeString,
  pg_stats: typeString,
  pg_subscription: typeString,
  pg_subscription_rel: typeString,
  pg_tables: typeString,
  pg_tablespace: typeString,
  pg_timezone_abbrevs: typeString,
  pg_timezone_names: typeString,
  pg_transform: typeString,
  pg_trigger: typeString,
  pg_ts_config: typeString,
  pg_ts_config_map: typeString,
  pg_ts_dict: typeString,
  pg_ts_parser: typeString,
  pg_ts_template: typeString,
  pg_type: typeString,
  pg_user: typeString,
  pg_user_mapping: typeString,
  pg_user_mappings: typeString,
  pg_views: typeString,
  trigger: typeString,
  tsm_handler: typeString,
  bit: typeString,
  bpchar: typeString,
  cidr: typeString,
  inet: typeString,
  void: typeString,
  float4: typeNumber,
  float8: typeString,
  int2vector: typeString,
  int4range: typeString,
  int2: typeNumber,
  int4: typeNumber,
  int8range: typeString,
  int8: typeString,
  money: typeString,
  numeric: typeString,
  jsonb: typeJson,
  json: typeJson,
  oid: typeNumber,
  regclass: typeString,
  regconfig: typeString,
  regdictionary: typeString,
  regnamespace: typeString,
  regoper: typeString,
  regoperator: typeString,
  regproc: typeString,
  regprocedure: typeString,
  regrole: typeString,
  regtype: typeString,
  box: typeString,
  path: typeString,
  polygon: typeString,
  circle: {
    type: 'ObjectLiteralConstant',
    items: [
      { name: 'x', type: typeNumber },
      { name: 'y', type: typeNumber },
      { name: 'radius', type: typeNumber },
    ],
  } as TypeObjectLiteralConstant,
  line: typeString,
  lseg: typeString,
  point: {
    type: 'ObjectLiteralConstant',
    items: [
      { name: 'x', type: typeNumber },
      { name: 'y', type: typeNumber },
    ],
  } as TypeObjectLiteralConstant,
  abstime: typeString,
  date: typeDate,
  time: typeString,
  timestamp: typeDate,
  timestamptz: typeDate,
  timetz: typeDate,
  bool: typeBoolean,
  tsrange: typeString,
  numrange: typeString,
  tstzrange: typeString,
  oidvector: typeString,
  record: typeString,
  refcursor: typeString,
  serial8: typeNumber,
  serial4: typeNumber,
  serial2: typeNumber,
  text: typeString,
  tsquery: typeString,
  tsvector: typeString,
  txid_snapshot: typeString,
  unknown: typeUnknown,
  varbit: typeString,
  varchar: typeString,
  xml: typeString,
  null: typeNull,
};

export const unaryOperatorTypes: { [type in UnaryOperatorTag['value']]: TypeConstant } = {
  '+': typeNumber,
  '-': typeNumber,
  NOT: typeBoolean,
  ISNULL: typeBoolean,
  NOTNULL: typeBoolean,
};

export const binaryOperatorTypes: {
  [type in BinaryOperatorTag['value']]: Array<[left: TypeConstant, right: TypeConstant, result: TypeConstant]>;
} = {
  '^': [[typeNumber, typeNumber, typeNumber]],
  '%': [[typeNumber, typeNumber, typeNumber]],
  '+': [
    [typeNumber, typeNumber, typeNumber],
    [typeDate, typeString, typeDate],
  ],
  '-': [
    [typeNumber, typeNumber, typeNumber],
    [typeJson, typeString, typeJson],
    [typeJson, arr(typeString), typeJson],
    [typeDate, typeString, typeDate],
    [typeDate, typeDate, typeDate],
  ],
  '/': [[typeNumber, typeNumber, typeNumber]],
  '*': [
    [typeNumber, typeNumber, typeNumber],
    [typeNumber, typeString, typeString],
    [typeDate, typeString, typeDate],
  ],
  OR: [[typeAny, typeAny, typeBoolean]],
  AND: [[typeAny, typeAny, typeBoolean]],
  '||': [
    [typeString, typeString, typeString],
    [typeJson, typeJson, typeJson],
  ],
  '>=': [
    [typeBoolean, typeBoolean, typeBoolean],
    [typeDate, typeDate, typeBoolean],
    [typeNumber, typeNumber, typeBoolean],
  ],
  '<=': [
    [typeBoolean, typeBoolean, typeBoolean],
    [typeDate, typeDate, typeBoolean],
    [typeNumber, typeNumber, typeBoolean],
  ],
  '>': [
    [typeBoolean, typeBoolean, typeBoolean],
    [typeDate, typeDate, typeBoolean],
    [typeNumber, typeNumber, typeBoolean],
  ],
  '<': [
    [typeBoolean, typeBoolean, typeBoolean],
    [typeDate, typeDate, typeBoolean],
    [typeNumber, typeNumber, typeBoolean],
  ],
  '=': [
    [typeNumber, typeNumber, typeBoolean],
    [typeDate, typeDate, typeBoolean],
    [typeString, typeString, typeBoolean],
    [typeBoolean, typeBoolean, typeBoolean],
    [typeJson, typeJson, typeBoolean],
  ],
  '!=': [
    [typeNumber, typeNumber, typeBoolean],
    [typeDate, typeDate, typeBoolean],
    [typeString, typeString, typeBoolean],
    [typeBoolean, typeBoolean, typeBoolean],
    [typeJson, typeJson, typeBoolean],
  ],
  '<>': [
    [typeNumber, typeNumber, typeBoolean],
    [typeDate, typeDate, typeBoolean],
    [typeString, typeString, typeBoolean],
    [typeBoolean, typeBoolean, typeBoolean],
    [typeJson, typeJson, typeBoolean],
  ],
  IN: [[typeAny, typeAny, typeBoolean]],
  '@@': [[typeString, typeString, typeBoolean]],
  LIKE: [[typeString, typeString, typeBoolean]],
  ILIKE: [[typeString, typeString, typeBoolean]],
  IS: [[typeAny, typeAny, typeBoolean]],
  '->': [
    [typeJson, typeNumber, typeJson],
    [typeJson, typeString, typeJson],
  ],
  '->>': [
    [typeJson, typeNumber, typeString],
    [typeJson, typeString, typeString],
  ],
  '#>': [[typeJson, arr(typeString), typeJson]],
  '#-': [[typeJson, arr(typeString), typeJson]],
  '#>>': [[typeJson, arr(typeString), typeString]],
  '?': [[typeJson, typeString, typeBoolean]],
  '?|': [[typeJson, arr(typeString), typeBoolean]],
  '?&': [[typeJson, arr(typeString), typeBoolean]],
  '@>': [
    [typeString, typeString, typeBoolean],
    [typeJson, typeJson, typeBoolean],
  ],
  '<->': [[typeString, typeString, typeString]],
  '<@': [
    [typeString, typeString, typeBoolean],
    [typeJson, typeJson, typeBoolean],
  ],
  '|': [
    [typeJson, typeJson, typeBoolean],
    [typeString, typeString, typeString],
  ],
  '&': [[typeString, typeString, typeString]],
  '#': [[typeString, typeString, typeString]],
  '~': [[typeString, typeString, typeString]],
  '~*': [[typeString, typeString, typeString]],
  '!~': [[typeString, typeString, typeString]],
  '!~*': [[typeString, typeString, typeString]],
  '<<': [[typeString, typeNumber, typeString]],
  '>>': [[typeString, typeNumber, typeString]],
  OVERLAPS: [[typeAny, typeAny, typeBoolean]],
  'AT TIME ZONE': [
    [typeDate, typeString, typeDate],
    [typeAny, typeString, typeDate],
  ],
  'IS DISTINCT FROM': [[typeAny, typeAny, typeBoolean]],
  'IS NOT DISTINCT FROM': [[typeAny, typeAny, typeBoolean]],
};

export interface TypeSpreadConstant {
  type: 'SpreadConstant';
  items: TypeConstant;
}
