name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DATABASE: potygen
          POSTGRES_USER: potygen
          POSTGRES_PASSWORD: dev-pass
        ports:
          - 5432:5432
        options: --name postgres --health-cmd pg_isready  --health-interval 10s  --health-timeout 5s  --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Initialize Database
        run: cat init.sql | docker exec --interactive postgres psql postgres://potygen:dev-pass@postgres:5432/potygen
      - name: Initialize Version Specific Database
        run: cat pg-version/v13/init-version.sql | docker exec --interactive postgres psql postgres://potygen:dev-pass@postgres:5432/potygen
      - name: Initialize Bookstore Example
        run: cat examples/bookstore/init.sql | docker exec --interactive postgres psql postgres://potygen:dev-pass@postgres:5432/potygen
      - uses: ./.github/actions/yarn-install
      - run: yarn build
      - run: yarn lint
      - run: yarn test:general --runInBand --ci
      - run: yarn test:13 --runInBand --ci
        env:
          POSTGRES_CONNECTION: postgres://potygen:dev-pass@localhost:5432/potygen
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
