name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container: node:16

    steps:
      - uses: actions/checkout@v2
      - uses: danielweller-swp/postgresql-action@v2
        with:
          postgresql version: '11'
          postgresql db: 'potygen'
          postgresql user: 'potygen'
          postgresql password: 'dev-pass'
          postgresql init scripts: './initdb.d'
      - name: Install Postgres Client (psql)
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client
      - name: Initialze Database
        run: psql postgres://potygen:dev-pass@localhost:5432/potygen -c 'SELECT * FROM all_types;'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test --runInBand --ci
        env:
          POSTGRES_CONNECTION: postgres://potygen:dev-pass@localhost:5432/potygen
