name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DATABASE: potygen
          POSTGRES_USER: potygen
          POSTGRES_PASSWORD: dev-pass
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 6
          --name postgres

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Initialze Database
        run: docker exec -it postgres psql postgres://potygen:dev-pass@postgres:5432/potygen -c 'SELECT * FROM all_types'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test --runInBand --ci
        env:
          POSTGRES_CONNECTION: postgres://potygen:dev-pass@localhost:5432/potygen
