name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container: node:16

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DATABASE: potygen
          POSTGRES_USER: potygen
          POSTGRES_PASSWORD: dev-pass
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Initialze Database
        run: psql -f init.sql postgresql://potygen:dev-pass@localhost:5432/potygen
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test --runInBand --ci --verbose
